##
GET http://localhost:8000/api/user
Accept: application/json
Authorization: Bearer 35|kCEqcQGZ2piDbMmJvzSJROtYHMXfYvSIx3qFXVpxac3eccd9

### Register a new user
POST http://localhost:8000/api/register
Accept: application/json
Content-Type: application/json

{
  "name": "Aouad mohammed",
  "email": "user1@example.com",
  "password": "password123",
  "role": "user"
}

### Login a user
POST http://localhost:8000/api/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123"
}



### Contact
POST http://localhost:8000/api/contacts
Accept: application/json
Content-Type: application/json

{
  "name": "Aouad Mohammed",
  "email": "aouad6@gmail.com",
  "phone": "0689104243",
  "message": "test tsest"
}




### Get all cars 
GET http://localhost:8000/api/cars?is_available=true
Authorization: Bearer 32|dlWnai2yNoBmIzeklWIDp2p9CO2dSCOoOnWbBdUNf4b32a7e
Accept: application/json


### Create a new car 
POST http://localhost:8000/api/cars
Authorization: Bearer 24|rEu9vh6XgukDv3mxXfCuat8UvPSieJ7wajwac1qYb3bdce2d
Accept: application/json
Content-Type: application/json

{
  "brand": "Toyota",
  "model": "Corolla",
  "year": 2020,
  "price_per_day": 50,
  "is_available": 1,
  "image": "https://example.com/toyota-corolla.jpg"
}

### Get a specific car
GET http://localhost:8000/api/cars/71
Authorization: Bearer 23|L0tWx1nYUmjiA1dJGVJnAypYV1AEjyanazscatG7c50f3ebd
Accept: application/json


### Update a car 
PUT http://localhost:8000/api/cars/71
Authorization: Bearer 24|rEu9vh6XgukDv3mxXfCuat8UvPSieJ7wajwac1qYb3bdce2d
Accept: application/json
Content-Type: application/json

{
  "brand":"hsi",
}

### Delete a car (requires authentication)
DELETE http://localhost:8000/api/cars/71
Authorization: Bearer 23|L0tWx1nYUmjiA1dJGVJnAypYV1AEjyanazscatG7c50f3ebd
Accept: application/json


### Create a new booking 
POST http://localhost:8000/api/bookings
Authorization: Bearer 26|GMAFoaegkahoq2QvrulCIVJxDWK820sIu8n4NEEXbec5fa83
Accept: application/json
Content-Type: application/json


{
  "user_id": 63,
  "car_id": 70,
  "start_date": "2023-10-01",
  "end_date": "2023-10-05",
  "total_price": 250
}

### Get all bookings 
GET http://localhost:8000/api/bookings
Authorization: Bearer 28|uDgExG5spMthDfb2MpN3BZLcjqZJPPzO9k3FQI4p603ad35b
Accept: application/json


### Get a specific booking 
GET http://localhost:8000/api/bookings/1
Accept: application/json


### Update a booking
PUT http://localhost:8000/api/bookings/6
Accept: application/json
Content-Type: application/json


{
  "total_price": 789
}

### Delete a booking 
DELETE http://localhost:8000/api/bookings/51
Authorization: Bearer 8|o7HFlSvJnMh3CnxmriuAorP3bEJkzf4ZBCMfTKWe52cf3bf4
Accept: application/json


### Logout the user (requires authentication)
POST http://localhost:8000/api/logout
Accept: application/json
Authorization: Bearer 5|cLUFL2iEohxvm4Qd8nOlt4EPnEL0Pl01AEmMa8G520c700da

### Get the authenticated user's profile (requires authentication)
GET http://localhost:8000/api/profile
Accept: application/json
Authorization: Bearer 96|nP6U8DusfpONX2uvB2wkBaS7JzPsZkLtJeyGJBIOa66147a7



